services:
  db:
    image: brunoyujitaka/proj_ext_database:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: "venuste"
    ports:
      - "3307:3306"
    restart: unless-stopped