services:
  backend:
    image: brunoyujitaka/proj_ext_backend:latest
    environment:
      NOME: "root"
      SENHA: "venuste"
      BUCKET: "bucket-imagem-teste"
      DB_HOST: "10.0.0.200"
      DB_PORT: "3307"
      RABBIT_HOST: "10.0.0.10"
    ports:
      - "8080:8080"
    restart: unless-stopped
  consumer:
    image: brunoyujitaka/proj_ext_consumer:latest
    restart: unless-stopped